version: '3.8'

services:
  
  backend:
    image: uday830/expense-sage-app-backend:latest
    ports:
      - "8080:8080"
    env_file:
      - ./backend/application/.env
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - postgres
      - redis
    networks:
      - app-network
  frontend:
    image: uday830/expense-sage-app-frontend:latest
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - app-network

  postgres:
    image: postgres:15-alpine
    container_name: postgres_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data

    networks:
      - app-network

  redis:
    image: redis:7-alpine
    container_name: redis_cache
    restart: always
    ports:
       - "6379:6379"
    volumes:
      - redisdata:/data
    networks:
      - app-network

volumes:
  pgdata:
  redisdata:
  
networks:
  app-network:
    driver: bridge