name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
      SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'temurin'
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install backend dependencies and build
        run: |
          cd project-repo/backend/application
          mvn clean install -DskipTests
          
      - name: Install frontend dependencies and build
        run: |
          cd project-repo/frontend
          npm install
          npm run build

      - name: Run unit tests
        run: mvn test

      - name: Build Docker images
        run: |
          docker-compose build

      - name: Push Docker images to local Docker
        run: |
          docker-compose up -d
